output_dir: /root/stock_price_prediction/output_dir
stock_code: None
dataset:
  date: "2018-08-01"
training:
  epochs: 100
eval:
  buy_trans_fee: 1.0006
  sell_trans_fee: 0.9994
  model_dir: /path/to/model_dir
  date: "2018-08-01"